; generated by tools/gen_hid_proxy.py: every hid.dll export jumps to the real function
EXTERN g_hidReal:QWORD
.code
stub_HidD_FlushQueue PROC
    jmp qword ptr [g_hidReal + 0]
stub_HidD_FlushQueue ENDP
stub_HidD_FreePreparsedData PROC
    jmp qword ptr [g_hidReal + 8]
stub_HidD_FreePreparsedData ENDP
stub_HidD_GetAttributes PROC
    jmp qword ptr [g_hidReal + 16]
stub_HidD_GetAttributes ENDP
stub_HidD_GetConfiguration PROC
    jmp qword ptr [g_hidReal + 24]
stub_HidD_GetConfiguration ENDP
stub_HidD_GetFeature PROC
    jmp qword ptr [g_hidReal + 32]
stub_HidD_GetFeature ENDP
stub_HidD_GetHidGuid PROC
    jmp qword ptr [g_hidReal + 40]
stub_HidD_GetHidGuid ENDP
stub_HidD_GetIndexedString PROC
    jmp qword ptr [g_hidReal + 48]
stub_HidD_GetIndexedString ENDP
stub_HidD_GetInputReport PROC
    jmp qword ptr [g_hidReal + 56]
stub_HidD_GetInputReport ENDP
stub_HidD_GetManufacturerString PROC
    jmp qword ptr [g_hidReal + 64]
stub_HidD_GetManufacturerString ENDP
stub_HidD_GetMsGenreDescriptor PROC
    jmp qword ptr [g_hidReal + 72]
stub_HidD_GetMsGenreDescriptor ENDP
stub_HidD_GetNumInputBuffers PROC
    jmp qword ptr [g_hidReal + 80]
stub_HidD_GetNumInputBuffers ENDP
stub_HidD_GetPhysicalDescriptor PROC
    jmp qword ptr [g_hidReal + 88]
stub_HidD_GetPhysicalDescriptor ENDP
stub_HidD_GetPreparsedData PROC
    jmp qword ptr [g_hidReal + 96]
stub_HidD_GetPreparsedData ENDP
stub_HidD_GetProductString PROC
    jmp qword ptr [g_hidReal + 104]
stub_HidD_GetProductString ENDP
stub_HidD_GetSerialNumberString PROC
    jmp qword ptr [g_hidReal + 112]
stub_HidD_GetSerialNumberString ENDP
stub_HidD_Hello PROC
    jmp qword ptr [g_hidReal + 120]
stub_HidD_Hello ENDP
stub_HidD_SetConfiguration PROC
    jmp qword ptr [g_hidReal + 128]
stub_HidD_SetConfiguration ENDP
stub_HidD_SetFeature PROC
    jmp qword ptr [g_hidReal + 136]
stub_HidD_SetFeature ENDP
stub_HidD_SetNumInputBuffers PROC
    jmp qword ptr [g_hidReal + 144]
stub_HidD_SetNumInputBuffers ENDP
stub_HidD_SetOutputReport PROC
    jmp qword ptr [g_hidReal + 152]
stub_HidD_SetOutputReport ENDP
stub_HidP_GetButtonArray PROC
    jmp qword ptr [g_hidReal + 160]
stub_HidP_GetButtonArray ENDP
stub_HidP_GetButtonCaps PROC
    jmp qword ptr [g_hidReal + 168]
stub_HidP_GetButtonCaps ENDP
stub_HidP_GetCaps PROC
    jmp qword ptr [g_hidReal + 176]
stub_HidP_GetCaps ENDP
stub_HidP_GetData PROC
    jmp qword ptr [g_hidReal + 184]
stub_HidP_GetData ENDP
stub_HidP_GetExtendedAttributes PROC
    jmp qword ptr [g_hidReal + 192]
stub_HidP_GetExtendedAttributes ENDP
stub_HidP_GetLinkCollectionNodes PROC
    jmp qword ptr [g_hidReal + 200]
stub_HidP_GetLinkCollectionNodes ENDP
stub_HidP_GetScaledUsageValue PROC
    jmp qword ptr [g_hidReal + 208]
stub_HidP_GetScaledUsageValue ENDP
stub_HidP_GetSpecificButtonCaps PROC
    jmp qword ptr [g_hidReal + 216]
stub_HidP_GetSpecificButtonCaps ENDP
stub_HidP_GetSpecificValueCaps PROC
    jmp qword ptr [g_hidReal + 224]
stub_HidP_GetSpecificValueCaps ENDP
stub_HidP_GetUsageValue PROC
    jmp qword ptr [g_hidReal + 232]
stub_HidP_GetUsageValue ENDP
stub_HidP_GetUsageValueArray PROC
    jmp qword ptr [g_hidReal + 240]
stub_HidP_GetUsageValueArray ENDP
stub_HidP_GetUsages PROC
    jmp qword ptr [g_hidReal + 248]
stub_HidP_GetUsages ENDP
stub_HidP_GetUsagesEx PROC
    jmp qword ptr [g_hidReal + 256]
stub_HidP_GetUsagesEx ENDP
stub_HidP_GetValueCaps PROC
    jmp qword ptr [g_hidReal + 264]
stub_HidP_GetValueCaps ENDP
stub_HidP_GetVersionInternal PROC
    jmp qword ptr [g_hidReal + 272]
stub_HidP_GetVersionInternal ENDP
stub_HidP_InitializeReportForID PROC
    jmp qword ptr [g_hidReal + 280]
stub_HidP_InitializeReportForID ENDP
stub_HidP_MaxDataListLength PROC
    jmp qword ptr [g_hidReal + 288]
stub_HidP_MaxDataListLength ENDP
stub_HidP_MaxUsageListLength PROC
    jmp qword ptr [g_hidReal + 296]
stub_HidP_MaxUsageListLength ENDP
stub_HidP_SetButtonArray PROC
    jmp qword ptr [g_hidReal + 304]
stub_HidP_SetButtonArray ENDP
stub_HidP_SetData PROC
    jmp qword ptr [g_hidReal + 312]
stub_HidP_SetData ENDP
stub_HidP_SetScaledUsageValue PROC
    jmp qword ptr [g_hidReal + 320]
stub_HidP_SetScaledUsageValue ENDP
stub_HidP_SetUsageValue PROC
    jmp qword ptr [g_hidReal + 328]
stub_HidP_SetUsageValue ENDP
stub_HidP_SetUsageValueArray PROC
    jmp qword ptr [g_hidReal + 336]
stub_HidP_SetUsageValueArray ENDP
stub_HidP_SetUsages PROC
    jmp qword ptr [g_hidReal + 344]
stub_HidP_SetUsages ENDP
stub_HidP_TranslateUsagesToI8042ScanCodes PROC
    jmp qword ptr [g_hidReal + 352]
stub_HidP_TranslateUsagesToI8042ScanCodes ENDP
stub_HidP_UnsetUsages PROC
    jmp qword ptr [g_hidReal + 360]
stub_HidP_UnsetUsages ENDP
stub_HidP_UsageListDifference PROC
    jmp qword ptr [g_hidReal + 368]
stub_HidP_UsageListDifference ENDP
END
