#!/usr/bin/env python3
"""gen_hid_proxy: writes the hid.dll forwarding layer from the system hid.dll's export table.

  src/hid.def        exports with the system DLL's names and ordinals, each bound to a stub
  src/hid_stubs.asm  one stub per export: jmp through g_hidReal[i] (x64 MASM)
  src/hid_names.h    the export names in the same order, for GetProcAddress

The stubs jump, they do not call, so every argument, return value and error code is the real DLL's. Needs pefile
(pip install pefile). Run it again only if Windows ever adds an export to hid.dll.
"""
import os
import pefile

here = os.path.dirname(os.path.abspath(__file__))
src = os.path.join(here, "..", "src")
pe = pefile.PE(os.path.join(os.environ["WINDIR"], "System32", "hid.dll"), fast_load=True)
pe.parse_data_directories(directories=[pefile.DIRECTORY_ENTRY["IMAGE_DIRECTORY_ENTRY_EXPORT"]])
exports = [(e.name.decode(), e.ordinal) for e in pe.DIRECTORY_ENTRY_EXPORT.symbols if e.name]
if any(e.forwarder for e in pe.DIRECTORY_ENTRY_EXPORT.symbols):
    raise SystemExit("hid.dll has forwarded exports; the stub layout does not cover them")

with open(os.path.join(src, "hid.def"), "w", newline="\r\n") as f:
    f.write("; generated by tools/gen_hid_proxy.py from System32\\hid.dll\nLIBRARY hid\nEXPORTS\n")
    for name, ordinal in exports:
        f.write("    %s=stub_%s @%d\n" % (name, name, ordinal))

with open(os.path.join(src, "hid_stubs.asm"), "w", newline="\r\n") as f:
    f.write("; generated by tools/gen_hid_proxy.py: every hid.dll export jumps to the real function\n")
    f.write("EXTERN g_hidReal:QWORD\n.code\n")
    for i, (name, _) in enumerate(exports):
        f.write("stub_%s PROC\n    jmp qword ptr [g_hidReal + %d]\nstub_%s ENDP\n" % (name, i * 8, name))
    f.write("END\n")

with open(os.path.join(src, "hid_names.h"), "w", newline="\r\n") as f:
    f.write("// generated by tools/gen_hid_proxy.py: hid.dll export names in stub order\n#pragma once\n")
    f.write("static const char *const kHidNames[] = {\n")
    for name, _ in exports:
        f.write('    "%s",\n' % name)
    f.write("};\nstatic const int kHidCount = %d;\n" % len(exports))
print("%d exports written" % len(exports))
